#!/bin/sh
throne &
sleep 3
udiskie --notify --smart-tray &
~/.fehbg &
/usr/lib/xfce-polkit/xfce-polkit &
dunst &
picom &
mpv --volume=40 --no-video /home/slats/.config/qtile/resources/boot.wav &
/home/slats/.config/qtile/scripts/redshift &
